echo

diff --git a/.github/workflows/swagger_export.yaml b/.github/workflows/swagger_export.yaml
--- a/.github/workflows/swagger_export.yaml
+++ b/.github/workflows/swagger_export.yaml
@@ -27,4 +27,8 @@ jobs:
       - name: Download nexus metadata
         run: |
          STATUSCODE=$(curl -s -L ${SERVER_URL}/${PREFIX}${commons} --write-out '%{http_code}' --output commons_swagger.json)
-         echo $STATUSCODE
+         if test $STATUSCODE -ne 200; then
+           echo "ERROR: commons_swagger.json : download Error. Status code : ${STATUSCODE}"
+           exit 1
+         else
+           echo "commons_swagger.json download OK"
